### ISSUE TITLE
Compiling flexavr and flashing it to the FlexTrak board

### ISSUE THREAD

**Issue by 001Mario** [daveake/flexavr#1]
I wanted to do some debugging for a custom ground station, as well as adding some features, but I am am having issues creating a `.ino.hex` file and flashing it to the FlexTrak board. What would be the best approach for this?

**Comment by daveake** [comment]
Depends.  What I do is install Arduino on a PC, and copy the resulting file
to the Pi, then program from there using AVRDude.  There's a programming
script for the later in this repo.

**Comment by 001Mario** [comment]
Found the script, thank you so much for the hint. I'll try.

**Comment by 001Mario** [comment]
Your suggestion worked a few times (thanks again!), but I think I accidentally crashed the bootloader on the Atmega chip as I'm getting an error message (`avrdude: stk500_getparm(): (a) protocol error, expect=0x14, resp=0x00
`) while running the `a` script. Any advise on resetting or reflashing the bootloader? I tried flashing the `flexavr.ino.with_bootloader.hex` file from this repo, but I get the same error as a result.

**Comment by daveake** [comment]
If you've wiped the bootloader then you can't reprogram over serial, i.e.
from the Pi, so AVRDude will give an error.  At that point you would need
to program the board from a programmer and not over serial.

I don't think it's possible to overwrite the bootloader from the
bootloader, so are you sure?

**Comment by 001Mario** [comment]
Would indeed be a positive message if the bootloader is still fine - I assumed that I broke it due to the error message I got. 

When compiling and exporting the code out of the Arduino IDE, the IDE is creating two files - one of them is titled `flexavr.ino.hex`, while the other one is named `flexavr.ino.with_bootloader.hex`. I flashed the first one a few times (no issues at all), and I was also able the revert back to the original code from this repo. During my last try, I accidentally (and probably out of stupidity) flashed the `flexavr.ino.with_bootloader.hex`-file, and since then I'm completely stuck with the error message above. I tried flashing both hex files from this repo to revert back to a working state, but no success so far.

Any ideas how I can revert to the default?

**Comment by daveake** [comment]
Replacing the bootloader shouldn't leave it with a bootloader, so I don't
really understand what's happened.  That said the sequence you describe
does make it sound like something went wrong at that last step.

The board has a special programmer connector, but it's unlikely you have
the matching cable, so there best thing would be to send the board to
Uputronics or to me for reprogramming.

I'm away on holiday till the weekend.

Dave

**Comment by 001Mario** [comment]
Do you have some wiring documentation for the programming header, and  - if yes - could you send this to me? I think I could try to build a adapter / or buy based on this and (try to) do the reprogramming myself.
Really appreciate your input, thanks a lot! Have a nice holiday & cheers, Mario

**Comment by daveake** [comment]
Check with a Anthony re the hardware please.

Dave

**Comment by 001Mario** [comment]
After some investigation today, I found the SPI pins on the board, soldered a connection to it and managed to restore the bootloader using [this tutorial](https://www.torsten-traenkner.de/linux/raspberry/arduino.php) (written in german, sorry) - overall, the board is now again working as it was shipped. I'm now also again able to flash software using the `a` script from this repo.

However, I'm not able to run software I compiled on my own (the `flexavr.ino.hex` from this repo is running without issues). Therefore, I suppose I have some issue(s) with my settings. Currently I'm compiling and exporting the `.hex`-file from the Arduino IDE (with settings Board Arduino Nano, Processor ATmega328P). What settings can you recommend?
Additionally, I needed to install the `I2C`-library manually, I choose [this one](https://github.com/ninjablocks/arduino/tree/master/I2C) - not sure if this is the right one though. 

Cheers, Mario

**Comment by daveake** [comment]
You need this one - https://github.com/rambo/I2C

**Comment by 001Mario** [comment]
Thanks a lot, I updated the library. Additionally, I changed the board to an Arduino Mini and set the CPU speed to 8MHz as suggested [here](https://github.com/daveake/flextrak/issues/1#issuecomment-818879467) - I think this was the final piece to the puzzle.

Cheers, Mario
